### ISSUE TITLE
Need clipping 2x for one enter into notes

### ISSUE THREAD

**Issue by yardstudio** [penge/my-notes#239] opened 2021-05-04 13:12 UTC
I have installed Chrome extension and need 2x clip page content for 1x save

**Comment by penge** [comment] 2021-05-04 13:38
I am afraid I don't understand, what do you need to do twice?

**Comment by yardstudio** [comment] 2021-05-04 13:42
> I am afraid I don't understand, what do you need to do twice?

Simply said, 

first clip doing nothing, only second the same step copy selected text to note

I must doing this step completelly twice for successfully save selected text into note
http://www.yardstudio.eu/printscreens/2021-05-04_15-42-02.png

**Comment by penge** [comment] 2021-05-04 13:54
Now I understand. I see. Let me have a look at it. I mark this a bug.

**Comment by penge** [comment] 2021-05-05 19:42
@yardstudio 
The problem is now fixed. Next version 3.8.1 should be available in about 2 days.

**Closed** 2021-05-05 21:00 UTC
Labels: bug
