### ISSUE TITLE
Notes are nowhere to be found.

### ISSUE THREAD

**Issue by Voltric-Witherin** [penge/my-notes#162] opened 2020-12-02 00:15 UTC
I cannot seem to access my notes. I have tried multiple methods of opening them but none work. They randomly stopped appearing a couple of days ago.

**Comment by penge** [comment] 2020-12-05 09:56
How many notes do you have? In terms of size, do you think it's about 5MB? (This can be checked in Google Drive folder if Google Drive Sync is enabled).

**Comment by Voltric-Witherin** [comment] 2020-12-05 19:33
I only had like 3 notes. Don't you need to manually upload it to Google Drive though. I didn't usually click the button so the notes on my drive are old. 

I cannot even access the extension's settings.

**Comment by penge** [comment] 2020-12-05 20:19
Upload is manual, yes. It seems that reaching the size quota didn't happen here and it isn't the cause.  
Can I ask you to answer few more questions? It might help us to identify the problem.

1. Can you still the list of notes?
2. Can you open some of them or none?
3. What browser are you using?
4. Could you access extension's settings before?
5. Did you have many images in the notes?

**Comment by Voltric-Witherin** [comment] 2020-12-05 22:42
No

None

Chrome

Yes

No images

**Comment by penge** [comment] 2020-12-05 23:23
So you see a blank page? Have you tried to use a Custom theme?

Try to open:

`chrome-extension://lkeeogfaiembcblonahillacpaabmiop/themes/custom/index.html`

And if anything is there, erase it and hit Save.

**Comment by penge** [comment] 2020-12-06 00:07
I have tried the following scenario:

1. I customize Custom theme and put empty spaces there, or something invalid and hit save. Still using Light theme though.
2. Then I went back to Options and enabled Custom theme, previously edited in step 1.
3. Notes and Options went blank because the Custom theme input was invalid.

I have prepared a patch that will fix this behavior (soon in version 3.5) and even if Custom theme is something invalid, it would continue to work and be visible, so the changes can be set back.

**Comment by Voltric-Witherin** [comment] 2020-12-06 19:23
Yes, the pages are blank. 
There was nothing in the Custom theme box. I was using the dark theme though.

**Comment by penge** [comment] 2020-12-06 20:34
Try to open **Developer Console**. Use `Option + ⌘ + J` (on macOS), or `Shift + CTRL + J` (on Windows/Linux). More [here](https://balsamiq.com/support/faqs/browserconsole/#:~:text=To%20open%20the%20developer%20console,(on%20Windows%2FLinux).).

Open My Notes and My Notes Options and see if there are any red messages (stands for errors) in the console. Send them here.

Also, run the following command:

```
chrome.storage.local.get(["theme", "customTheme"], local => console.log(local.theme, local.customTheme?.length))
```

Send here the output of the above command.

You may try to check on your notes by running this command (but keep this output just for yourself):

```
chrome.storage.local.get(["notes"], local => console.log(local.notes))
```

If you uninstalled/reinstalled the extension, notes are gone unless you had a Google Drive backup. This is because reinstalling the extensions removes the data.

**Comment by Voltric-Witherin** [comment] 2020-12-06 23:34
My notes red messages: 
Unchecked runtime.lastError: IO error: .../LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)
notes.html:1 
Error handling response: TypeError: Cannot destructure property 'notification' of 'local' as it is undefined.
    at chrome-extension://lkeeogfaiembcblonahillacpaabmiop/notes.js:80:5

My notes options red messages: 
options.html:1 Unchecked runtime.lastError: IO error: .../LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)
options.html:1 Error handling response: TypeError: Cannot destructure property 'font' of 'local' as it is undefined.
    at chrome-extension://lkeeogfaiembcblonahillacpaabmiop/options.js:24:11


Do I run the command by typing it into the box that pops up when I use this keyboard shortcut combination: Windows key + R
If so, it says "windows cannot find 'chrome.storage.local.get(["theme",'. Make sure you typed the name correctly, and then try again."

**Comment by penge** [comment] 2020-12-06 23:48
Thank you. Try to restart the browser.

**Comment by Voltric-Witherin** [comment] 2020-12-07 06:32
I just updated it and nothing.

**Comment by penge** [comment] 2020-12-07 09:08
Are you trying to open My Notes in normal window or incognito? Due to some reason, it cannot access any of data, based on the messages you sent here. The other commands I mentioned to try, would have to be entered into the console right after the > symbol. More at https://balsamiq.com/support/faqs/browserconsole/#google-chrome. But we can tell these woudn't work either as it is not providing **'local'** at all. I am trying to figure out why it stopped working for you where even reinstalling the extension didn't help. Doesn't make sense. Have you meanwhile installed some other extension?

**Comment by Voltric-Witherin** [comment] 2020-12-08 16:57
I'm using a normal window. I have not installed another extension.

**Closed** 2020-12-09 20:38 UTC
Labels: bug

**Comment by penge** [comment] 2020-12-09 20:43
Closing as this is obviously a problem of your browser.

**Comment by Voltric-Witherin** [comment] 2020-12-09 21:28
It works when I use chrome on other devices.

**Comment by penge** [comment] 2020-12-09 21:43
on what device it's not working?

**Comment by Voltric-Witherin** [comment] 2020-12-09 22:57
Desktop pc
