### ISSUE TITLE
Focus on the address bar by default when you open a new tab

### ISSUE THREAD

**Issue by soul-ride** [penge/my-notes#91] opened 2020-05-29 20:10 UTC
Hi @penge ,
With the last update My Notes is focused (instead of address bar focused) automatically 50% of the time when I open the new tab with CTRL+T. There are 2 problems with this:
- It's not always focused/unfocused (not consistent). It's not clear when your cursor will be focused on the address bar and when it will be focused on the note. Looks like it's being focused on the note when you didn't open a new page for some time (it also seems like page render takes a little bit longer in these cases, feels like the page was cleaned up from the memory).
- I propose to focus on the address bar by default. Usually people open new tabs more often than writing the notes. Maybe add an option to switch this behavior.

**Comment by penge** [comment] 2020-05-30 01:30
Hi @soul-ride 

Thank you for reporting this. There will be a fix in `3.0.4`, it will be like this:

- `CTRL + T` => _NO_ **autofocus**, not even try to (because it is not guaranteed)
    - sometimes it took me 10 tabs, sometimes 50, before I first saw the focused note, instead of the address bar; it is not consistent even for me, although not so much

- `CTRL + SHIFT + M` => **autofocus**, but only if new tab override is not enabled

There are some limits that are reached already, therefore this has no proper solution where the **autofocus** on `CTRL + T` would be possible. 
This brings me back to: https://github.com/penge/my-notes/issues/58

**Comment by penge** [comment] 2020-05-30 14:03
Hi @soul-ride 

Thank you for reporting this. I was able to reproduce it.

In `3.0.4`:
- `CTRL + T` will have guaranteed focus of the address bar
- autofocus will be removed

There is no better solution. This is the way.

**Comment by penge** [comment] 2020-05-30 14:07
Hi @soul-ride 

Solution will come in `3.0.4`. The solution will be to remove the note autofocus.

Unfortunately, there is no better solution that would be consistent.

**Comment by penge** [comment] 2020-05-30 16:50
The reasons why autofocus has to be removed:

- autofocus tries to focus the note on `CTRL + T`, and sometimes it succeeds (1 of every 10 tabs, 1 of every 50 tabs, but can be more common - thanks @soul-ride for reporting). The keyboard focus is not guaranteed here, nor reliable. This is a limitation that comes with how the extensions are created. More about this is here: https://developer.chrome.com/extensions/override

    - **Detail:** When new tab is overriden, its URL changes (from what is a default new tab page). The change of the URL causes the URL to be selected (have the focus). Trying to focus the content of the page, does not work.

- there is no way to have a consistent solution

    - **Detail:** If My Notes is open with `CTRL + T` or `CTRL + SHIFT + M`, the behavior couldn't be guaranteed to be the same in both cases. Although `CTRL + SHIFT + M` doesn't have the limitations (because default new tab is not overriden in this case, rather, a fresh new tab is created).

---

**Not related to this issue.**

There are some more limitations that don't have a solution. Not related to this issue, but I will mention them at least. When a new tab is overriden, these steps happen if done programatically:
1. Title is `New Tab`
2. Title is changed to `chrome-search://local-ntp/local-ntp.html` which is the location of the default New Tab
3. Title is changed to My Notes, or the note title (if a note was open on the last visit)

It would be great, if this could be solved as well. This limitation doesn't happen if new tab is overriden declaratively (in `manifest.json`). That's how it was in the past, but it has one huge drawback - it was a setting that couldn't be optional. Me personally, I prefer `CTRL + SHIFT + M` but want to support both solutions (new tab override enabled, new tab override disabled).

The other limitation is, an inability to use a variable in the `manifest.json` which makes it hard to maintain different settings for other environments, without bringing a build step into the play. An example: `client_id` required by Google Drive, which is different for the published My Notes, and for My Notes developed locally.

Another limitation is, there is no way to test some things, unless published. Therefore even my best efforts are challenged. As example, functionality that is bound to the extension's ID. The ideal would be, if the extension installed for the development, could have a custom ID, an ID that I could set on 2 computers. I hope Google is reading this :)

**Comment by penge** [comment] 2020-05-30 17:35
@soul-ride `3.0.4` is on its way. Today or tomorrow available.

**Comment by soul-ride** [comment] 2020-05-30 18:26
Thank you.

**Comment by soul-ride** [comment] 2020-06-01 14:16
Hi @penge ,
This issue is still present after update to 3.0.4 :(

For me its reproducible like that:
1. Open new tab
2. Open new tab again -> address bar focused
3. Open new tab as many times as you want -> address bar focused
4. Switch to other tabs. Spend some time (few minutes) browsing some sites as usual.
5. Press CTRL+T or + button -> My Notes focused instead of the address bar.

I've tried to re-open the browser - same thing.

**Comment by penge** [comment] 2020-06-01 14:22
I wonder how this is possible. Let me try those steps.

**Comment by penge** [comment] 2020-06-01 14:37
I have bad news.

I think this doesn't have a solution. I tried it and yes, it happens time to time.

Here's the bad news. I tried it even when I commented out the whole script, leaving just a dummy blank white page. It still happened, time to time.

I feel like I am dealing with something that's just Chrome behavior or sort off.

At this point I don't know about the solution :(

**Comment by soul-ride** [comment] 2020-06-01 14:37
I've recorded the screencast - https://drive.google.com/file/d/1p_9sFB_f4grJHXbWjrapZzLK8eqlBMho/view

1:55 - open new tab and it's focuses on the address bar
4:37 - open new tab and it's focused on the My Notes

This issue was not observed before the 3.0.2 - 3.0.3.

**Comment by penge** [comment] 2020-06-01 14:39
This is what happened during the testing :D 

<img width="1440" alt="Screen Shot 2020-06-01 at 4 38 05 PM" src="https://user-images.githubusercontent.com/907255/83420080-60ebcc80-a426-11ea-9729-02319a33c908.png">

It seems like it's more prone to be buggy on NEW WINDOW, rather than new tab.

**Comment by penge** [comment] 2020-06-01 14:42
I am going to try out version 3.0 how that goes.

**Comment by penge** [comment] 2020-06-01 14:44
Happened even in 3.0 :((

**Comment by soul-ride** [comment] 2020-06-01 14:44
For me, it never happens when you open many new tabs. It's opposite actually, when you do not open a new tab for a while. 
Feels like Chrome kinda suspend or cleans up the extension from the memory and then reloads it and focuses on it. Maybe there are ways to avoid such behavior.

**Comment by penge** [comment] 2020-06-01 14:47
Happened even when I opened two new windows sequentially.

First one had focused address bar, second did not.

Something is causing address to be not selected.

**Comment by penge** [comment] 2020-06-01 14:51
Checked the video. Same happened to me. It also happened very randomly.

**Comment by penge** [comment] 2020-06-01 14:57
Now opened new window and created 4 tabs. 3 of them didn't have the address bar selected.

**Comment by soul-ride** [comment] 2020-06-01 14:59
If I keep a tab with My Notes opened and browse other sites, I do not face this issue when I open an additional new tab.
Overall, this behavior is pretty consistent. Basically, whenever I spend few minutes on the website to read article or watch video and My Notes is closed, I will face this issue next time when I open new tab.
I have 32GB of memory so it shouldn't happen due to insufficient memory. However it really feels like Chrome is doing something in the background with this extension.
My Chrome version 83.0.4103.61 (Official Build) (64-bit).

**Comment by penge** [comment] 2020-06-01 15:02
I faced this issue, even when My Notes was already open. Like tried to open more, more...

It's pretty weird. I think it has something to do with the internals, when `update` is called. Seems like sometimes it wait's for the URL to change, and it is selected. And sometimes it just didn't catch it, and therefore is not selected.

Here are the internals:
```js
// pendingUrl is available since Chrome 79; url is a fallback
if (tab.pendingUrl === "chrome://newtab/" || tab.url === "chrome://newtab/") {
  chrome.tabs.update(tab.id, { url: "/notes.html", autoDiscardable: false });
}
```

**Comment by penge** [comment] 2020-06-01 15:07
<img width="960" alt="Screen Shot 2020-06-01 at 5 06 20 PM" src="https://user-images.githubusercontent.com/907255/83422750-49aede00-a42a-11ea-8ee5-9afdd694dbaa.png">

Not a solution, but you can try opening My Notes with some keyboard shortcut. And when you need New Tab, the current `CTRL + T` would work as default.

**Comment by penge** [comment] 2020-06-01 15:12
The things that can be unloaded when not used, is the background script. But anyway, it gets started as soon as needed again. But that doesn't change how it works. Html and JS is still the same.

One last thing I can try, is to have the background script pernamently running, although that's not advised.

**Comment by soul-ride** [comment] 2020-06-01 15:15
When I open My Notes with the shortcut (let's say Ctrl + Shift + M) it's always not focused, neither on My Notes or address bar.

**Comment by penge** [comment] 2020-06-01 15:16
^^ yeah, that's how it should be acutally

**Comment by penge** [comment] 2020-06-01 15:18
I think I can bring autofocus back then.

**Comment by penge** [comment] 2020-06-01 15:27
I now opened a hundred tabs before it randomly happened again.

<img width="1440" alt="Screen Shot 2020-06-01 at 5 26 36 PM" src="https://user-images.githubusercontent.com/907255/83424774-2c2f4380-a42d-11ea-8a53-1b5e1775803a.png">

**Comment by soul-ride** [comment] 2020-06-01 18:32
It feels like we are testing different things here. At least for the issue I've reported, it never happens when you have new tab opened. It happens when there is no opened new tabs (and My Notes) and you do not open new tabs for several minutes. 
For example now I do not have any new tabs opened. If I open new tab right after completing this comment, it will be focused on the My Notes (not the address bar). However next new tab which I will open will be focused on the address bar.
Honestly saying, this thing is driving me crazy since you never know for sure where where your cursor will be upon opening the new tab (and it definitely should be on the address bar by default since browsing webpages is primary function of the web browser).

Where can I get earlier versions of My Notes so I could test them?
Thanks.

**Comment by soul-ride** [comment] 2020-06-01 18:42
Ok, I've found a way to consistently reproduce it:
1. Open the webpage (this github page for example)
2. Open timer on your phone
3. Open new page with Ctrl+T
4. Close it (so you returned to this github page) and immediagely start timer
5. If you wait for less than 14.99 seconds and press Ctrl+T, cursor will be focused on the address bar
6. If you wait for more than 15.00 seconds and press Ctrl+T, cursor will be out of focus (so whatever you print do not appear on the screen at all).

**Comment by penge** [comment] 2020-06-01 20:23
@soul-ride Thanks a lot for these steps. It made it crystal clear where the root of the problem is.

I followed the steps for about 10 times, every time the address bar was selected. It turns out, it can be 15 seconds (your case), or maybe 30 seconds (my case), or 5 seconds, 10 minutes, or on first tab, 80th, 120th.

It all boils down to this.

<img width="414" alt="Screen Shot 2020-06-01 at 9 31 06 PM" src="https://user-images.githubusercontent.com/907255/83448284-fd779400-a451-11ea-9639-f32132917d6c.png">
<img width="414" alt="Screen Shot 2020-06-01 at 9 30 47 PM" src="https://user-images.githubusercontent.com/907255/83448290-fea8c100-a451-11ea-981d-546266daef11.png">

**"Inactive"** means the background page (with a script inside) was unloaded. Can happen for any of the reasons above, as more memory resources are needed. Although you have 32 GB RAM, it still tries to allocate as much as it can, based on some rules. That explains why it happened after you visited some other pages.

The 100% way how to reproduce this, is to disable the extension and enable it again (the blue button). What will happen then, the extension will be **"Inactive"**, until used again.

If the first use would be opening the **New Tab**, the background page would be loaded for the first time, and the problem with the address bar would happen.

If the first use would be opening **Options** instead, then the second use would be opening **New Tab**, while background page still loaded, then it would hinder the problem, it wouldn't occur.

It all comes down to internally used `chrome.tabs.update` which causes those problems, if it's the first thing run after the background page is loaded. It has to be problem with Chrome, because unless background page wasn't unloaded, there is no problem whatsoever.

The good news. I have found a "solution", that works all the time. It's not what I would want, because it's not best practices.

https://developer.chrome.com/extensions/background_migration

> Only under rare circumstances should an extension have a persistent background, as they constantly consume system resources and can cause a strain on lower-powered devices.

> // Recommended
>    "persistent": false,

The solution is to make background page pernament. We can call it a fix and put in in `3.0.5`.

**Comment by soul-ride** [comment] 2020-06-01 23:07
> It all boils down to this.

Indeed. I'm glad root cause was found :) 

> it can be 15 seconds (your case), or maybe 30 seconds (my case), or 5 seconds, 10 minutes, or on first tab, 80th, 120th.

I've tested it on 3 different machines with totally different configurations on different networks (all Windows though). It's always exactly 15 seconds. Maybe there is some difference in this mechanism on Mac and PC.

> If the first use would be opening the New Tab, the background page would be loaded for the first time, and the problem with the address bar would happen.
If the first use would be opening Options instead, then the second use would be opening New Tab, while background page still loaded, then it would hinder the problem, it wouldn't occur.

This is not reproducible for me. When I follow the steps, then close My Notes, background.html still becomes inactive after 15 seconds.

> I have found a "solution", that works all the time. It's not what I would want, because it's not best practices

I believe in case with your extension it's reasonable solution. Most of extension replacing new page are just some pictures or some icon grids purposed for mouse interactions. Your extension however can be used (and probably mostly used like that) without touching the mouse at all. When it loses focus and you forced to move your hands from keyboard to mouse, it totally destroys the "interaction flow". We shouldn't always follow recommendations, right? :)

Waiting on update. Thanks.

**Comment by penge** [comment] 2020-06-01 23:37
This is definitely an OS / Chrome combination thing.

I just tried it on Chrome OS (where I originally developed My Notes), and there these problems don't happen at all.

In Chrome OS, even innactive background page, doesn't cause any problem, and the very first New Tab has the address bar selected.

That may be reason this has been overlooked or I couldn't comprehend what the hell it's causing it. Either it works, or not.

In Windows it might be always 15 seconds. If you disable/enable the extension, it should be innactive from the beginning, and the problem should be reproduceable right away (no need to wait 15 seconds, it's the innactive state causing it). But maybe when you disable/enable the extension in Windows, it maybe isn't innactive from the beginning, so you had to wait first. IDK. But definitely it happens only when innactive (you can check that by having extensions page open and every time it gets innactive, it causes the problem, then innactive disappears, and all good, until innactive again).

I know it is definitely annoying if address bar wouldn't be selected. Even if it happens just 1 of 100.

The best I can do, is to make background script persistent. In Chrome OS ot will look the same, but on Windows / OSX it will solve this.

Maybe in future this will be solved, I check forums if there is a mentioning of this.

So yeah. Good news. At least there is a solution! Best practices are one thing, but make it work is more important. It will be fixed during today so tomorrow it can be published as 3.0.5 ;)

**Comment by penge** [comment] 2020-06-02 13:44
Here's a persistent background page (doesn't get into Innactive state).

![persistent](https://user-images.githubusercontent.com/907255/83527348-f8fdba80-a4e7-11ea-8a4b-4801c76fc9d0.gif)

**Closed** 2020-06-02 14:33 UTC
Labels: bug

**Comment by penge** [comment] 2020-06-03 15:53
Hi @soul-ride, is everything working well after the recent update?

**Comment by soul-ride** [comment] 2020-06-03 16:35
Hi @penge ,
Yes, I do not observe that issue anymore. Thanks.

**Comment by penge** [comment] 2020-06-03 16:39
That's great!
