### ISSUE TITLE
Curser skips to top of page

### ISSUE THREAD

**Issue by Alexbba** [penge/my-notes#188] opened 2021-02-11 18:58 UTC
Am using a chromebook. The curser skips to the top of the page in the middle of editing/entering text.

**Comment by penge** [comment] 2021-02-13 13:54
Thank you for reporting this. I have a Chromebook so I'll try this tomorrow.

Did this happen for the first time or also in the past?
Is it happening when you write text, or when you are trying to do something else?
Is it happening every time, or sometimes?

I have tried it now on a Mac, and haven't experienced the issue. But will try Chromebook tomorrow.

**Comment by Alexbba** [comment] 2021-02-13 14:26
It's been like this for at least a month. Only when I'm trying to write. Every time, whether on a new note or on a previously created one.

**Comment by penge** [comment] 2021-02-13 14:49
Thank you, I will look at it.

**Comment by penge** [comment] 2021-02-15 17:55
I have tried it on Chromebook and haven't experienced the issue. There must be some special case or steps that lead to this. Any idea how to  try it out?

**Comment by penge** [comment] 2021-02-22 18:12
Hi @Alexbba 
My Notes version 3.6 is now on the way, currently in review on Web Store. Please, let me know if this issue remains there or no longer happening. Version 3.6 should be available on Web Store in 1-2 days.

**Comment by Alexbba** [comment] 2021-03-10 19:55
Seems to be good now!

**Comment by Alexbba** [comment] 2021-04-15 19:57
Thanks for the 3.7 update! Actually, it has started skipping to the beginning/top  again as before (still using my CHROMEBOOK) very erratically, and only saving (even deleting!) things haphazardly, it seems.

**Comment by penge** [comment] 2021-04-15 20:23
Hi @Alexbba 

I haven't experienced the problem. Is there some series of steps to follow when it happens?

**Comment by bhavant** [comment] 2021-04-19 15:46
Hi @penge,
The issue happens on mac too. There are no specific steps. Just keep typing and the cursor jumps to the start of the note!
See the video below...
https://user-images.githubusercontent.com/3638898/115264499-5866b800-a104-11eb-9749-c0d96e5f4305.mp4

**Comment by penge** [comment] 2021-04-19 16:54
The video and the finding with the breakpoint WAS EXTREMELY HELPFUL! Thanks a lot @bhavant!
I think I know now where to look to solve this. Giving it priority so we can have it asap.

**Comment by penge** [comment] 2021-04-19 18:37
**Here's an explanation on how it works and what was causing the problem:**

Note can be updated by the user (for the majority of the time), but note can also be updated by the Context menu (when you use it to save text to note). If Context menu was used to save text to a currently open note, that note should be reloaded (that causes the cursor to jump to the beginning). To find out if the note was updated by the user or by the Context menu (to know if it should be reloaded or not), there was a use of `setTimeout` that would, for a short time, set `"notesChangedBy"` in local storage.

Long story short. I was NOT able to reproduce the problem as there was probably a running condition to it, but knowing about `innerHTML` and `setTimeout` was very helpful to identify the problem. One of these two could happen:
A) when `"notesChangedBy"` is set, note was changed by the user
B) when `"notesChangedBy"` is NOT set, note was changed by the Context menu

There was an event that after the note was saved, checked if `"notesChangedBy"` is set (point B) and refreshed the note. If this mentioned event was fired and meanwhile during its execution `"notesChangedBy"` was reset (removed from local storage by the timer), it considered the note to be changed by the Context menu (again point B) and refreshed the note, while it shoud not.

I have changed how this works now, updated the service worker to tell if the note was updated by the Context menu, that flips the checking other way around. Service worker sets `setFromBackground` to `true`. Timer used before to set `"notesChangedBy"` could go away, also the whole part about `"notesChangedBy"` (including saving it to local storage).
Now, a new timer was defined that would reset `setFromBackground` after 1 second, but this time from a safe place that woudn't case this problem.

I hope I didn't go too much into detail but it's fixed now. I have as well ready everything for the upcoming version 3.8. I shall release it all together on this Tuesday or Wednesday (meaning it should be on Web Store by the of the week).

Thank you very much again for brinking this topic back so we could solve it.

@Alexbba @bhavant 

If you would like to help to test My Notes 3.8 prior to its release, you are very welcome and I would share the upcoming version here.

**Comment by bhavant** [comment] 2021-04-19 19:42
@penge the DOM was getting refreshed; your explanation makes sense now. I can pull the code and test but as I understand it will not sync with drive. Either way I use almost every day so even after release I will reach if I see something. Thank you for building this app. It is very very useful.

**Comment by penge** [comment] 2021-04-19 20:10
@bhavant Nice, I will create PR soon and put it to master.

Google Drive Sync can work locally, custom client ID for oauth2 needs to be provided (if not provided, then it works only if installed from Web Store). There are two ways: create one of your own at Google Cloud / APIs & Services / Credentials / OAuth 2.0 Client IDs, or I can simply provide you one.

Then, it would work like this:

```
$ npm install
$ export MY_NOTES_CLIENT_ID=<CLIENT_ID>
$ npm run develop  # or npm run develop-watch
```

Client ID is always tied to a specific extension ID, that is why if not provided, default is used, and default is tied to Web Store My Notes. That is why Google Drive Sync woudn't work locally by default (as it will have different extension ID to the one on Web Store), but if client ID for that extensions ID is created and provided, it will work even locally.

**Comment by penge** [comment] 2021-04-20 11:41
Fix is now ready.

Regarding Google Drive Sync, I will update README soon on how to run it locally.

**Closed** 2021-04-20 11:43 UTC
Labels: bug, priority
